from __future__ import annotations

from typing import Protocol

from app.modules.obligations.domain.entities import Obligation


class ObligationRepository(Protocol):
    async def add(self, obligation: Obligation) -> None: ...
    async def get(self, obligation_id: str) -> Obligation: ...
    async def update(self, obligation: Obligation) -> None: ...
    async def list_by_profile(self, profile_id: str) -> list[Obligation]: ...
    async def delete(self, profile_id: str, obligation_id: str) -> None: ...
