from __future__ import annotations

from typing import Protocol

from app.modules.consent.domain.entities import CifLink, Consent


class ConsentRepository(Protocol):
    async def add(self, consent: Consent) -> None: ...
    async def get(self, consent_id: str) -> Consent: ...
    async def update(self, consent: Consent) -> None: ...
    async def list_for_cif(self, cif: str) -> list[Consent]: ...
    async def list_all(self) -> list[Consent]: ...


class CifLinkRepository(Protocol):
    async def add(self, link: CifLink) -> None: ...
    async def list_for_profile(self, profile_id: str) -> list[CifLink]: ...
    async def list_for_cif(self, cif: str) -> list[CifLink]: ...
